### ISSUE TITLE
Feature req: Temporary Buffs

### ISSUE THREAD

**Issue by MagerlinC** [LukasTvegaard/deadlands-companion#4]
Add a feature which allows the user to input a temporary buff on their character.

The buff should have a turn-based duration, and should show up in the party overview. 

A cool addition would be to be able to tick all buff durations down a turn, either for the character or the entire party.

**Comment by LukasTvegaard** [comment]
First version closed by: https://github.com/LukasTvegaard/deadlands-companion/pull/5. 

Plans for future support described in: https://github.com/LukasTvegaard/deadlands-companion/issues/8
